[mypy]
python_version = 3.11
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
disallow_any_generics = False
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_no_return = True
check_untyped_defs = True

[mypy-tests.*]
ignore_errors = True

[mypy-project_pipelines.*]
ignore_errors = True

[mypy-shared.guardrails]
ignore_errors = True

[mypy-shared.data_sources.base]
ignore_errors = True

[mypy-shared.runtime]
ignore_errors = True

[mypy-run_project]
ignore_errors = True

